spring.application.name=intellibiz-backend
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/intellibiz}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
